---
- name: Install Apache HTTPD and deploy a sample HTML file
  hosts: all
  become: yes  # Use sudo to escalate privileges
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: Ensure httpd is running and enabled
    service:
      name: httpd
      state: started
      enabled: yes
