---
- hosts: all
  gather_facts: yes  # Gather facts for all hosts
  tasks:
    - name: Display the distribution name
      debug:
        msg: "Distribution name: {{ ansible_distribution }}"

    - name: Display the kernel version
      debug:
        msg: "Kernel version: {{ ansible_kernel }}"

- hosts: all
  gather_facts: true  # Gather facts only if not already available
  tasks:
    - name: Display the default IPv4 address
      debug:
        msg: "Default IPv4 address: {{ ansible_default_ipv4.address }}"
