---
- hosts: all
  tasks:

    - name: Debug a string
      debug:
        msg: "Hello, World!"

    - name: Debug a variable
      vars:
        my_variable: "This is a variable"
      debug:
        var: my_variable

    - name: Debug a data structure
      vars:
        my_dict:
          name: Alice
          age: 25
          city: New York
      debug:
        var: my_dict
