---
- hosts: all
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
